export const PURCHASES_LIST_REQUEST = "PURCHASES_LIST_REQUEST";
export const PURCHASES_LIST_SUCCESS = "PURCHASES_LIST_SUCCESS";
export const PURCHASES_LIST_FAIL = "PURCHASES_LIST_FAIL";

export const PURCHASES_CREATE_REQUEST = "PURCHASES_CREATE_REQUEST";
export const PURCHASES_CREATE_SUCCESS = "PURCHASES_CREATE_SUCCESS";
export const PURCHASES_CREATE_FAIL = "PURCHASES_CREATE_FAIL";

export const PURCHASES_UPDATE_REQUEST = "PURCHASES_UPDATE_REQUEST";
export const PURCHASES_UPDATE_SUCCESS = "PURCHASES_UPDATE_SUCCESS";
export const PURCHASES_UPDATE_FAIL = "PURCHASES_UPDATE_FAIL";

export const PURCHASES_DELETE_REQUEST = "PURCHASES_DELETE_REQUEST";
export const PURCHASES_DELETE_SUCCESS = "PURCHASES_DELETE_SUCCESS";
export const PURCHASES_DELETE_FAIL = "PURCHASES_DELETE_FAIL";
